/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/db`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/club` | `/club`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/league` | `/league`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/market` | `/market`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/squad` | `/squad`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tactics` | `/tactics`; params?: Router.UnknownInputParams; } | { pathname: `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/components`; params?: Router.UnknownOutputParams; } | { pathname: `/db`; params?: Router.UnknownOutputParams; } | { pathname: `/match`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/club` | `/club`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/league` | `/league`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/market` | `/market`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/squad` | `/squad`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tactics` | `/tactics`; params?: Router.UnknownOutputParams; } | { pathname: `/player/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/components${`?${string}` | `#${string}` | ''}` | `/db${`?${string}` | `#${string}` | ''}` | `/match${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/club${`?${string}` | `#${string}` | ''}` | `/club${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/league${`?${string}` | `#${string}` | ''}` | `/league${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/market${`?${string}` | `#${string}` | ''}` | `/market${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/squad${`?${string}` | `#${string}` | ''}` | `/squad${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tactics${`?${string}` | `#${string}` | ''}` | `/tactics${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/db`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/club` | `/club`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/league` | `/league`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/market` | `/market`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/squad` | `/squad`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tactics` | `/tactics`; params?: Router.UnknownInputParams; } | `/player/${Router.SingleRoutePart<T>}` | { pathname: `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
